development:
  adapter: postgresql
  database: timer_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: timer_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: timer_production
  pool: 5
  timeout: 5000
